export const articles = [
  {
    id: 1,
    category: 'Ekip Liderliği',
    title: 'Belirsizlik Dönemlerinde Ekibinizi Nasıl Yönetirsiniz?',
    excerpt: '15 yıllık sahadan öğrendiklerimle belirsizliği yönetmenin somut yolları.',
    date: '2026-06-24',
  },
  {
    id: 2,
    category: 'Proje Yönetimi',
    title: 'Proje Başlangıç Toplantısını Doğru Yönetmek',
    excerpt: 'Kick-off toplantısı bir projenin kaderini belirler. Doğru sorular, net beklentiler ve güçlü bir başlangıç için pratik bir rehber.',
    date: '2026-06-10',
  },
  {
    id: 3,
    category: 'Program Yönetimi',
    title: 'Çoklu Proje Yönetiminde Önceliklendirme Sanatı',
    excerpt: 'Aynı anda 24 aktif projeyi yönetirken öğrendiklerim: Önceliklendirme, kaynak dengeleme ve odak kaybını önleme.',
    date: '2026-05-28',
  },
  {
    id: 4,
    category: 'Risk Yönetimi',
    title: 'Proje Risklerini Erken Tespit Etmenin 5 Yolu',
    excerpt: 'Risk yönetimi reaktif değil proaktif bir süreçtir. Sahadan öğrendiğim erken uyarı sinyalleri ve pratik müdahale yöntemleri.',
    date: '2026-05-14',
  },
  {
    id: 5,
    category: 'Dijital Dönüşüm',
    title: 'ERP Entegrasyon Projelerinde Sık Yapılan Hatalar',
    excerpt: 'SAP ve Oracle entegrasyon projelerinde karşılaştığım en yaygın tuzaklar ve bunlardan nasıl kaçınılır.',
    date: '2026-06-07',
  },
  {
    id: 6,
    category: 'Ekip Liderliği',
    title: 'Teknik Ekiplerle Etkili İletişim Kurmanın Yolları',
    excerpt: 'Yazılım geliştirici, analist ve test uzmanlarından oluşan ekiplerde iletişim köprüsü kurmak için kanıtlanmış yöntemler.',
    date: '2026-04-30',
  },
  {
    id: 7,
    category: 'Proje Yönetimi',
    title: 'Agile ve Waterfall: Hangisi Ne Zaman?',
    excerpt: 'Her projeye aynı metodoloji uygulanamaz. Fintech ve kurumsal yazılım projelerinden örneklerle doğru metodoloji seçimi.',
    date: '2026-04-15',
  },
  {
    id: 8,
    category: 'Paydaş Yönetimi',
    title: 'Zor Paydaşlarla Başa Çıkma Rehberi',
    excerpt: 'Her projede bir "zor paydaş" vardır. Direnci işbirliğine dönüştürmek için sahadan test edilmiş yaklaşımlar.',
    date: '2026-05-05',
  },
  {
    id: 9,
    category: 'Dijital Dönüşüm',
    title: 'Banka Entegrasyon Projelerinde Kritik Başarı Faktörleri',
    excerpt: 'Web servis ve SFTP entegrasyonlarında teknik ekip ile iş birimi arasındaki koordinasyonu sağlamanın yolları.',
    date: '2026-05-22',
  },
  {
    id: 10,
    category: 'Paydaş Yönetimi',
    title: 'Proje Başarısını Belirleyen Gizli Faktör: Paydaş Güveni',
    excerpt: 'Projeler çoğu zaman teknik nedenlerle değil, güven kaybı nedeniyle zorlaşır. Paydaş güvenini inşa etmenin dört temel davranışı.',
    date: '2026-06-26',
  },
];
